---
     environment: production
     address: 127.0.0.1
     port: 4567
     pid: /home/anil/public_html/cheatsweets/thin.pid
     rackup: /home/anil/public_html/cheatsweets/config.ru
     log: /home/anil/public_html/cheatsweets/thin.log
     max_conns: 1024
     timeout: 30
     max_persistent_conns: 512
     daemonize: true
