---
     environment: production
     address: 127.0.0.1
     port: 4567
     pid: /Users/anildigital/Code/sinatra/cheatsweets/thin.pid
     rackup: /Users/anildigital/Code/sinatra/cheatsweets/config.ru
     log: /Users/anildigital/Code/sinatra/cheatsweets/thin.log
     max_conns: 1024
     timeout: 30
     max_persistent_conns: 512
     daemonize: true
